<Project>
  <Import Project="$(MSBuildToolsPath)/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" />
  <PropertyGroup>
    <FerrumWeaveSdk>true</FerrumWeaveSdk>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <FerrumWeaveRepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../../..'))</FerrumWeaveRepoRoot>
  </PropertyGroup>
</Project>
