<Project>
  <Import Project="$(MSBuildToolsPath)/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" Condition="'$(UsingMicrosoftNETSdk)' != 'true'" />
  <PropertyGroup>
    <FerrumWeaveSdk>true</FerrumWeaveSdk>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <OutputType>Exe</OutputType>
    <FerrumWeaveRepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../../..'))</FerrumWeaveRepoRoot>
  </PropertyGroup>
</Project>
